displayName=WeCorpCC
author=Shimonos
description=Corporeal Beast helper for Boosting, Solo and Mass modes with player tracking, spec counters session statistics.
tags=corp,corporeal beast,corp beast,corporeal,boosting,mass,solo,pvm,osrs,wecorpcc
plugins=com.wecorpcc.WeCorpPlugin
version=1.0.0
build=standard
