displayName=WeCorpCC
author=WeCorpCC
description=Corp Beast helper for WeCorpCC - tracks players, specs, loot shares and more
tags=corp,corporeal beast,boosting,wecorp
plugins=com.wecorpcc.WeCorpPlugin
version=
build=standard