displayName=WeCorpCC
author=Hisham Abu Dahoud
description=Corporeal Beast helper with Boosting, Solo and Mass modes.
tags=corp,corporeal beast,boosting,mass,solo,wecorp,pvm
version=1.0.0
plugins=com.wecorpcc.WeCorpPlugin
build=standard
